### PR TITLE
update test case and fix test in multithreads environment

### LINKED ISSUE #182: tests failing locally, related to `ComputationalResources` ?
I am testing this package locally, on Julia 1.5, and I am getting a test failure on the following test: https://github.com/JuliaImages/ImageFiltering.jl/blob/6c0ea6b9d4a2b2223ab7c6d6cbec0a4ed551f86c/test/2d.jl#L341

because what actually gets thrown is a `TaskFailedException`. Full information is below.

I imagine there might be something different in my configuration that makes it use Tasks, and that it's not being used in CI? Whatever the case may be, it would be nice to get the tests to pass locally.

```julia
import ImageFiltering: imfilter, Kernel, Fill

A = ones(8, 8);
kern = Kernel.gaussian((1,1),(3,3));
imfilter(A, kern, Fill(0, (0,1)))
```

```
ERROR: TaskFailedException:
DimensionMismatch("requested indices (1:8, 0:9) and kernel indices (-1:1, 0:0) do not agree with indices of padded input, (1:8, 0:9)")
Stacktrace:
 [1] imfilter!(::ComputationalResources.CPU1{ImageFiltering.Algorithm.FIRTiled{2}}, ::TiledIteration.TileBuffer{Float64,2,2}, ::OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}}, ::OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}}, ::ImageFiltering.NoPad{Fill{Int64,2}}, ::Tuple{UnitRange{Int64},UnitRange{Int64}}) at /private/tmp/dev/ImageFiltering/src/imfilter.jl:980
 [2] macro expansion at /private/tmp/dev/ImageFiltering/src/imfilter.jl:867 [inlined]
 [3] (::ImageFiltering.var"#88#threadsfor_fun#41"{ComputationalResources.CPU1{ImageFiltering.Algorithm.FIRTiled{2}},Array{Float64,2},OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}},OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}},OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}},ImageFiltering.NoPad{Fill{Int64,2}},Array{Tuple{UnitRange{Int64},UnitRange{Int64}},1},Array{Array{Float64,2},1},UnitRange{Int64}})(::Bool) at ./threadingconstructs.jl:81
 [4] (::ImageFiltering.var"#88#threadsfor_fun#41"{ComputationalResources.CPU1{ImageFiltering.Algorithm.FIRTiled{2}},Array{Float64,2},OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}},OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}},OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}},ImageFiltering.NoPad{Fill{Int64,2}},Array{Tuple{UnitRange{Int64},UnitRange{Int64}},1},Array{Array{Float64,2},1},UnitRange{Int64}})() at ./threadingconstructs.jl:48
Stacktrace:
 [1] wait at ./task.jl:267 [inlined]
 [2] threading_run(::Function) at ./threadingconstructs.jl:34
 [3] macro expansion at ./threadingconstructs.jl:93 [inlined]
 [4] _imfilter_tiled_threads!(::ComputationalResources.CPU1{ImageFiltering.Algorithm.FIRTiled{2}}, ::Array{Float64,2}, ::OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}}, ::OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}}, ::OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}}, ::ImageFiltering.NoPad{Fill{Int64,2}}, ::Array{Tuple{UnitRange{Int64},UnitRange{Int64}},1}, ::Array{Array{Float64,2},1}) at /private/tmp/dev/ImageFiltering/src/imfilter.jl:863
 [5] _imfilter_tiled!(::ComputationalResources.CPUThreads{ImageFiltering.Algorithm.FIRTiled{2}}, ::Array{Float64,2}, ::OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}}, ::Tuple{OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}},OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}}}, ::ImageFiltering.NoPad{Fill{Int64,2}}, ::Array{Array{Float64,2},1}, ::Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}) at /private/tmp/dev/ImageFiltering/src/imfilter.jl:859
 [6] imfilter!(::ComputationalResources.CPUThreads{ImageFiltering.Algorithm.FIRTiled{2}}, ::Array{Float64,2}, ::OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}}, ::Tuple{OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}},OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}}}, ::ImageFiltering.NoPad{Fill{Int64,2}}, ::Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}) at /private/tmp/dev/ImageFiltering/src/imfilter.jl:778
 [7] imfilter! at /private/tmp/dev/ImageFiltering/src/imfilter.jl:775 [inlined]
 [8] imfilter! at /private/tmp/dev/ImageFiltering/src/imfilter.jl:716 [inlined]
 [9] imfilter!(::Array{Float64,2}, ::Array{Float64,2}, ::Tuple{OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}},OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}}}, ::Fill{Int64,2}, ::ImageFiltering.Algorithm.FIRTiled{2}) at /private/tmp/dev/ImageFiltering/src/imfilter.jl:612
 [10] imfilter! at /private/tmp/dev/ImageFiltering/src/imfilter.jl:606 [inlined]
 [11] imfilter at /private/tmp/dev/ImageFiltering/src/imfilter.jl:27 [inlined]
 [12] imfilter at /private/tmp/dev/ImageFiltering/src/imfilter.jl:10 [inlined]
 [13] imfilter(::Array{Float64,2}, ::OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}}, ::Fill{Int64,2}) at /private/tmp/dev/ImageFiltering/src/imfilter.jl:5
 [14] top-level scope at none:1
```

### PR DESCRIPTION
**Pull request by johnnychen94**
This PR consists of two independent commits.

closes #182

### CODE REVIEW

File: test/2d.jl [hunk 1]
```diff
@@ -334,10 +334,10 @@ end
...
     err = ArgumentError("$(typestring(Fill{Int,1}))(0, (3,), (3,)) lacks the proper padding sizes for an array with 2 dimensions")
     kern = Kernel.gaussian((1,1),(3,3))
-    @test_throws err imfilter(A, kern, Fill(0, (3,)))
+    @test_throws err imfilter(CPU1(), A, kern, Fill(0, (3,)))
     kernf = ImageFiltering.factorkernel(kern)
-    err = DimensionMismatch("requested indices (1:8, 0:9) and kernel indices $(axes(kernf[1])) do not agree with indices of padded input, (0:9, 1:8)")
-    @test_throws err imfilter(A, kern, Fill(0, (1,0)))
-    @test_throws DimensionMismatch imfilter(A, kern, Fill(0, (0,1)))
-    @test_throws DimensionMismatch imfilter(A, kern, Fill(0, (0,0)))
+    err = DimensionMismatch("output indices (OffsetArrays.IdOffsetRange(0:9), OffsetArrays.IdOffsetRange(1:8)) disagrees with requested indices (1:8, 0:9)")
```
Comment (timholy) [inline test/2d.jl:339]:
```suggestion
    err = DimensionMismatch("output indices (OffsetArrays.IdOffsetRange(0:9), OffsetArrays.IdOffsetRange(1:8)) disagree with requested indices (1:8, 0:9)")
```

("indices" is plural...parenthetically, English is **so** weird in that plural nouns get an `s` but verb agreement drops the `s`!)

**Review by timholy — APPROVED** [review]
